[package]
name = "gd32demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
gd32f3 = { version = "0.1.0-alpha.1", features = ["rt", "gd32f303"] }
